### ISSUE TITLE
An error is reported during installation, indicating that Organization already exists

### ISSUE THREAD

**Issue by Hkaisense** [paulpierre/RasaGPT#8]
Traceback (most recent call last):
  File "/app/api/seed.py", line 128, in <module>
    org_obj = create_org_by_org_or_uuid(
  File "/app/api/helpers.py", line 95, in create_org_by_org_or_uuid
    raise HTTPException(status_code=404, detail="Organization already exists")
fastapi.exceptions.HTTPException

**Comment by paulpierre** [comment]
hi @Hkaisense 

this is because you've ran the model migration already which is part of `make install`.

to continue where you left off run:
- `make run`
- `make seed` (if you wish to populate the db with dummy data)

alternatively if you want to do a fresh install again, first run `make db-reset` .. this will reinitialize the database (delete the postgres volume), migrate the models. be sure to run `make seed` for dummy data.

let me know if you have further issues
